# Generated by Django 4.1.5 on 2023-02-05 17:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_project_employees'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project_Employees',
            new_name='Project_Members',
        ),
    ]
