# Generated by Django 4.1.5 on 2023-02-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_project_employees_project_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_members',
            name='id_project',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project_members',
            name='id_user',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
