# Generated by Django 4.1.5 on 2023-01-31 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers_Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('employees_number', models.CharField(max_length=200)),
                ('adress', models.CharField(max_length=200)),
                ('company_type', models.CharField(default='customer', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier_Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('employees_number', models.CharField(max_length=200)),
                ('adress', models.CharField(max_length=200)),
                ('project_size', models.CharField(max_length=200)),
                ('expertise', models.CharField(max_length=50)),
                ('company_type', models.CharField(default='supplier', max_length=50)),
            ],
        ),
    ]
