# Generated by Django 4.1.5 on 2023-02-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_customers_company_company_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers_company',
            name='company_owner',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supplier_company',
            name='company_owner',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
