# Generated by Django 4.1.4 on 2023-02-06 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
        ('employees', '0003_alter_customer_employees_company_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_employees',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.customers_company'),
        ),
        migrations.AlterField(
            model_name='customer_employees',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
