# Generated by Django 4.1.5 on 2023-02-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_customer_employees_company_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_employees',
            name='user_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supplier_employees',
            name='user_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
