# Generated by Django 4.1.5 on 2023-01-28 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier_Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('employees_number', models.CharField(max_length=200)),
                ('adress', models.CharField(max_length=200)),
                ('project_size', models.CharField(max_length=200)),
                ('expertise', models.CharField(max_length=50)),
                ('company_type', models.CharField(default='supplier', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='delievery_service',
        ),
        migrations.AddField(
            model_name='profile',
            name='company_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
