# Generated by Django 4.1.5 on 2023-01-29 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customers_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='company_id',
            new_name='company_name',
        ),
    ]
