# Generated by Django 4.1.5 on 2023-01-31 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_company_id_profile_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='company_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='Customers_company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customers_company'),
        ),
        migrations.AddField(
            model_name='profile',
            name='Supplier_company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.supplier_company'),
        ),
    ]
