# Generated by Django 4.1.5 on 2023-01-31 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_profile_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Customers_company_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Supplier_company_id',
        ),
    ]
