# Generated by Django 4.1.5 on 2023-01-31 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('users', '0010_profile_customers_company_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Customers_company_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.customers_company'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Supplier_company_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.supplier_company'),
        ),
        migrations.DeleteModel(
            name='Customers_Company',
        ),
        migrations.DeleteModel(
            name='Supplier_Company',
        ),
    ]
