# Generated by Django 4.1.5 on 2023-02-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_profile_customers_company_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Customers_company_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Supplier_company_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
